version: '3.7'
services:
  web:
    build: .
    working_dir: /var/www/html
    depends_on: [ db ]
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - type: bind
        source: ./logs/httpd
        target: /var/log/httpd
      - type: bind
        source: ./logs/php_errors.log
        target: /var/log/php_errors.log

    ports:
      - "8001:80"
  db:
    image: mysql:latest
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  reverse-proxy:
    image: nginx:latest
    depends_on: [ web ]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - type: bind
        source: ./logs/nginx
        target: /etc/nginx/logs
    ports:
      - 80:80
      - 443:443
volumes:
  db-data:
    driver: local
